### ISSUE TITLE
Add Information about Electricity Demand

### ISSUE THREAD

**Issue by c0nb4** [TUB-DVG/djangoCesium#17]
## Ideas of solution

In the info box, I want two tabs. Single Family Houses and Mutli Family Houses 

First, residential display current text. 

![grafik](https://github.com/user-attachments/assets/271f44c0-5653-43b6-9fba-1c0e4eb8dbc9)

Below add a table:  
For Single Family Houses 

<html><body>
<h3>Durchschnittlicher Stromverbrauch pro Jahr – im Einfamilienhaus</h3><div class="table-wrapper">
Haushaltsgröße | Stromverbrauch | Stromverbrauch mit elektr. Warmwasserbereitung
-- | -- | --
1 Person | 2.400 kWh/Jahr | 2.700 kWh/Jahr
2 Personen | 3.000 kWh/Jahr | 3.500 kWh/Jahr
3 Personen | 3.600 kWh/Jahr | 4.500 kWh/Jahr
4 Personen | 4.000 kWh/Jahr | 5.100 kWh/Jahr
5 Personen | 5.000 kWh/Jahr | 6.300 kWh/Jahr

</div>
</body>
</html>

For Multi Family Houses 

<html><body>
<h3>Durchschnittlicher Stromverbrauch pro Jahr – im Mehrfamilienhaus</h3><div class="table-wrapper">
Haushaltsgröße | Stromverbrauch | Stromverbrauch mit elektr. Warmwasserbereitung
-- | -- | --
1 Person | 1.400 kWh/Jahr | 1.700 kWh/Jahr
2 Personen | 2.000 kWh/Jahr | 2.800 kWh/Jahr
3 Personen | 2.600 kWh/Jahr | 3.600 kWh/Jahr
4 Personen | 2.900 kWh/Jahr | 4.200 kWh/Jahr
5 Personen | 3.000 kWh/Jahr | 4.500 kWh/Jahr

</div>
</body>
</html>

## Workflow checklist

- [x] I am aware of the workflow in [CONTRIBUTING.md](../CONTRIBUTING.md)
- [x] I have created a branch for my feature

**Comment by nlongn22** [comment]
Updates on this issue can be found on the filip-update-districtgenerator.

**Comment by nlongn22** [comment]
@c0nb4 Hey, per discussion I've created two instances (each for SFH and MFH) with corresponding tables.
